spring:
  profiles:
    include: db,es
  messages:
    basename: messages
    cache-second: 3600
    encoding: UTF-8

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
